SELECT 
    DOMAIN,
    COUNT(*) AS EA,
    (SELECT COUNT(*) FROM PROFESSOR WHERE EMAIL IS NOT NULL) AS SUM_DOMAIN,
    TO_CHAR(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PROFESSOR WHERE EMAIL IS NOT NULL), '999.99')  "%"
FROM (
    SELECT 
        SUBSTR(EMAIL, INSTR(EMAIL, '@') + 1) AS DOMAIN
    FROM PROFESSOR
    WHERE EMAIL IS NOT NULL
    AND INSTR(EMAIL, '@') > 0
) DOMAINS
WHERE DOMAIN NOT IN ('example.com', 'university.org')
GROUP BY DOMAIN
ORDER BY DOMAIN;















